#디버깅 로그 블링블링하게 해줌
spring:
  output:
    ansi:
      enabled: always

  #Oracle DB 연결
  datasource:
    url: jdbc:oracle:thin:@C44M4IT64ZKKEISA_high?TNS_ADMIN=/Users/sanghyunkim/Oracle_instantclient10_1/Wallet_C44M4IT64ZKKEISA
    username: ADMIN
    password: Soldesk802!!
    driverClassName: oracle.jdbc.OracleDriver

#MyBatis 연결 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.app.ayofit.model
  mapper-locations: mybatis/**/*.xml

#디버깅 로그 레벨 설정
logging:
  level:
    #"[org.springframework.security]": TRACE
    "[com.app.ayofit]": DEBUG
    "[com.app.ayofit.mapper]": TRACE
